// blog-client/src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { KeycloakTokenParsed } from 'keycloak-js';
import { AuthRole } from 'src/app/enums/auth-role.enum';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent {

  public accessTokenParsed: KeycloakTokenParsed | undefined = undefined;
  public idTokenParsed: KeycloakTokenParsed | undefined = undefined;
  public refreshTokenParsed: KeycloakTokenParsed | undefined = undefined;

  constructor(
    private authService: AuthService,
  ) {
    this.accessTokenParsed = this.authService.getAccessTokenParsed();
    this.idTokenParsed = this.authService.getIdTokenParsed();
    this.refreshTokenParsed = this.authService.getRefreshTokenParsed();
  }

  public isAccessAllowed(): boolean {
    return this.authService.isUserInRole(AuthRole.Observer);
  }
}

<section class="dashboard">
    <mat-accordion multi>
        <mat-expansion-panel>
            <mat-expansion-panel-header>
                <mat-panel-title>Access Token</mat-panel-title>
                <mat-panel-description>OpenID Connect <mat-icon>key</mat-icon></mat-panel-description>
            </mat-expansion-panel-header>
            <div class="description">
                <p>A token that allows a client to access a specific resource to perform specific actions on behalf of the user.</p>
            </div>
            <pre *ngIf="accessTokenParsed">{{ accessTokenParsed | json }}</pre>
        </mat-expansion-panel>
    </mat-accordion>
    <mat-accordion>
        <mat-expansion-panel>
            <mat-expansion-panel-header>
                <mat-panel-title>Identity Token</mat-panel-title>
                <mat-panel-description>OpenID Connect <mat-icon>key</mat-icon></mat-panel-description>
            </mat-expansion-panel-header>
            <div class="description">
                <p>A token that provides identity information about the user.</p>
            </div>
            <pre *ngIf="idTokenParsed">{{ idTokenParsed | json }}</pre>
        </mat-expansion-panel>
    </mat-accordion>
    <mat-accordion>
        <mat-expansion-panel>
            <mat-expansion-panel-header>
                <mat-panel-title>Refresh Token</mat-panel-title>
                <mat-panel-description>OpenID Connect <mat-icon>key</mat-icon></mat-panel-description>
            </mat-expansion-panel-header>
            <div class="description">
                <p>A token used to request a new access token in cases where it is expired.</p>
            </div>
            <pre *ngIf="refreshTokenParsed">{{ refreshTokenParsed | json }}</pre>
        </mat-expansion-panel>
    </mat-accordion>
    <mat-accordion>
        <mat-expansion-panel [expanded]="true">
            <mat-expansion-panel-header>
                <mat-panel-title>App Data</mat-panel-title>
                <mat-panel-description>Access Control <mat-icon>account_circle</mat-icon></mat-panel-description>
            </mat-expansion-panel-header>
            <app-post-list *ngIf="isAccessAllowed()"></app-post-list>
        </mat-expansion-panel>
    </mat-accordion>
</section>

// issue-tracker-client/src/pages/Dashboard/Dashboard.tsx
import React, { useContext } from 'react';

import { Accordion, AccordionDetails, AccordionSummary, Box, Typography } from '@mui/material';
import KeyIcon from '@mui/icons-material/Key';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import AccountCircleIcon from '@mui/icons-material/AccountCircle';

import './Dashboard.scss';
import { AppContext } from '../../contexts/AppContext';

const Dashboard = () => {
  const appCtx = useContext(AppContext);
  
  return (
    <Box>
      <Accordion sx={{
        borderRadius: '4px',
        marginBottom: '16px',
        '::before': {
          display: 'none',
        }
      }}>
        <AccordionSummary
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel1a-content"
          id="panel1-header">
          <Typography sx={{
            flexGrow: 1,
            flexBasis: 0,
            dislay: 'flex',
            alignItems: 'center',
            marginRight: '16px',
            fontWeight: 500,
          }}>Access Token</Typography>
          <Typography sx={{
            flexGrow: 2,
            flexBasis: 0,
            display: 'flex',
            justifyContent: 'space-between',
            alignContent: 'center',
            marginRight: '16px',
            fontSize: '14px',
            fontWeight: 500,
            lineHeight: '24px',
            color: 'text.secondary',
            }}>
              OpenID Connect <KeyIcon />
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
        <div className="description">
          <p>A token that allows a client to access a specific resource to perform specific actions on behalf of the user.</p>
        </div>
        { appCtx.state.accessTokenParsed ? <pre>{JSON.stringify(appCtx.state.accessTokenParsed, null, 2)}</pre> : '' }
        </AccordionDetails>
      </Accordion>
      <Accordion sx={{
        borderRadius: '4px',
        marginBottom: '16px',
        '::before': {
          display: 'none',
        }
      }}>
        <AccordionSummary
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel1a-content"
          id="panel2-header">
          <Typography sx={{
            flexGrow: 1,
            flexBasis: 0,
            dislay: 'flex',
            alignItems: 'center',
            marginRight: '16px',
            fontWeight: 500,
          }}>Identity Token</Typography>
          <Typography sx={{
            flexGrow: 2,
            flexBasis: 0,
            display: 'flex',
            justifyContent: 'space-between',
            alignContent: 'center',
            marginRight: '16px',
            fontSize: '14px',
            fontWeight: 500,
            lineHeight: '24px',
            color: 'text.secondary',
            }}>
              OpenID Connect <KeyIcon />
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
        <div className="description">
          <p>A token that provides identity information about the user.</p>
        </div>
        { appCtx.state.idTokenParsed ? <pre>{JSON.stringify(appCtx.state.idTokenParsed, null, 2)}</pre> : '' }
        </AccordionDetails>
      </Accordion>
      <Accordion sx={{
        borderRadius: '4px',
        marginBottom: '16px',
        '::before': {
          display: 'none',
        }
      }}>
        <AccordionSummary
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel1a-content"
          id="panel3-header">
          <Typography sx={{
            flexGrow: 1,
            flexBasis: 0,
            dislay: 'flex',
            alignItems: 'center',
            marginRight: '16px',
            fontWeight: 500,
          }}>Refresh Token</Typography>
          <Typography sx={{
            flexGrow: 2,
            flexBasis: 0,
            display: 'flex',
            justifyContent: 'space-between',
            alignContent: 'center',
            marginRight: '16px',
            fontSize: '14px',
            fontWeight: 500,
            lineHeight: '24px',
            color: 'text.secondary',
            }}>
              OpenID Connect <KeyIcon />
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
        <div className="description">
          <p>A token used to request a new access token in cases where it is expired.</p>
        </div>
        { appCtx.state.refreshTokenParsed ? <pre>{JSON.stringify(appCtx.state.refreshTokenParsed, null, 2)}</pre> : '' }
        </AccordionDetails>
      </Accordion>
      <Accordion 
        sx={{
          borderRadius: '4px',
          '::before': {
            display: 'none',
          },
      }} defaultExpanded>
        <AccordionSummary
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel1a-content"
          id="panel4-header">
          <Typography sx={{
            flexGrow: 1,
            flexBasis: 0,
            dislay: 'flex',
            alignItems: 'center',
            marginRight: '16px',
            fontWeight: 500,
          }}>App Data</Typography>
          <Typography sx={{
            flexGrow: 2,
            flexBasis: 0,
            display: 'flex',
            justifyContent: 'space-between',
            alignContent: 'center',
            marginRight: '16px',
            fontSize: '14px',
            fontWeight: 500,
            lineHeight: '24px',
            color: 'text.secondary',
            }}>
              Access Control <AccountCircleIcon />
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
        <div className="description">
          <p>Test...</p>
        </div>
        </AccordionDetails>
      </Accordion>
    </Box>
  );
};

export default Dashboard;
